# Generated by Django 6.1 on 2026-09-07 21:11

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("tenants", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="RazorpayConnectAttempt",
            fields=[
                ("id", models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("state", models.CharField(max_length=64, unique=True)),
                ("consumed", models.BooleanField(default=False)),
                (
                    "tenant",
                    models.ForeignKey(db_index=False, on_delete=django.db.models.deletion.CASCADE, to="tenants.tenant"),
                ),
            ],
            options={
                "db_table": "payments_razorpay_connect_attempt",
                "abstract": False,
                "indexes": [models.Index(fields=["tenant", "created_at"], name="payments_ra_tenant__c4bba7_idx")],
            },
        ),
        migrations.CreateModel(
            name="RazorpayConnection",
            fields=[
                ("id", models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("razorpay_account_id", models.CharField(blank=True, default="", max_length=100)),
                ("access_token_encrypted", models.BinaryField()),
                ("refresh_token_encrypted", models.BinaryField()),
                ("token_expires_at", models.DateTimeField()),
                ("connected_at", models.DateTimeField(auto_now_add=True)),
                ("is_active", models.BooleanField(default=True)),
                (
                    "tenant",
                    models.ForeignKey(db_index=False, on_delete=django.db.models.deletion.CASCADE, to="tenants.tenant"),
                ),
            ],
            options={
                "db_table": "payments_razorpay_connection",
                "abstract": False,
                "indexes": [models.Index(fields=["tenant", "created_at"], name="payments_ra_tenant__589f9d_idx")],
                "constraints": [
                    models.UniqueConstraint(fields=("tenant",), name="unique_razorpay_connection_per_tenant")
                ],
            },
        ),
    ]
