# Generated by Django 6.1 on 2026-09-07 22:31

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("orders", "0004_order_payment_mode"),
        ("payments", "0001_initial"),
        ("tenants", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="razorpayconnection",
            name="auth_mode",
            field=models.CharField(
                choices=[("oauth", "OAuth"), ("direct_keys", "Direct Keys")], default="direct_keys", max_length=20
            ),
        ),
        migrations.AddField(
            model_name="razorpayconnection",
            name="webhook_secret",
            field=models.CharField(blank=True, default="", max_length=100),
        ),
        migrations.CreateModel(
            name="Payment",
            fields=[
                ("id", models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("razorpay_order_id", models.CharField(max_length=100, unique=True)),
                ("razorpay_payment_id", models.CharField(blank=True, default="", max_length=100)),
                (
                    "status",
                    models.CharField(
                        choices=[("created", "Created"), ("captured", "Captured"), ("failed", "Failed")],
                        default="created",
                        max_length=20,
                    ),
                ),
                ("amount", models.DecimalField(decimal_places=2, max_digits=10)),
                (
                    "order",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE, related_name="payment", to="orders.order"
                    ),
                ),
                (
                    "tenant",
                    models.ForeignKey(db_index=False, on_delete=django.db.models.deletion.CASCADE, to="tenants.tenant"),
                ),
            ],
            options={
                "db_table": "payments_payment",
                "abstract": False,
                "indexes": [models.Index(fields=["tenant", "created_at"], name="payments_pa_tenant__acd7cf_idx")],
            },
        ),
        migrations.CreateModel(
            name="WebhookEvent",
            fields=[
                ("id", models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("event_id", models.CharField(max_length=150, unique=True)),
                ("event_type", models.CharField(max_length=50)),
                (
                    "tenant",
                    models.ForeignKey(db_index=False, on_delete=django.db.models.deletion.CASCADE, to="tenants.tenant"),
                ),
            ],
            options={
                "db_table": "payments_webhook_event",
                "abstract": False,
                "indexes": [models.Index(fields=["tenant", "created_at"], name="payments_we_tenant__6e0718_idx")],
            },
        ),
    ]
