# Generated by Django 6.1 on 2026-09-09 15:58

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("billing", "0001_initial"),
        ("tenants", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="plan",
            name="razorpay_plan_id",
            field=models.CharField(blank=True, default="", max_length=100),
        ),
        migrations.CreateModel(
            name="Subscription",
            fields=[
                ("id", models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("razorpay_subscription_id", models.CharField(max_length=100, unique=True)),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("created", "Created"),
                            ("active", "Active"),
                            ("pending", "Pending"),
                            ("halted", "Halted"),
                            ("cancelled", "Cancelled"),
                            ("paused", "Paused"),
                            ("completed", "Completed"),
                        ],
                        default="created",
                        max_length=20,
                    ),
                ),
                ("current_period_end", models.DateTimeField(blank=True, null=True)),
                ("mandate_status", models.CharField(blank=True, default="", max_length=30)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "plan",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT, related_name="subscriptions", to="billing.plan"
                    ),
                ),
                (
                    "tenant",
                    models.ForeignKey(db_index=False, on_delete=django.db.models.deletion.CASCADE, to="tenants.tenant"),
                ),
            ],
            options={
                "db_table": "billing_subscription",
                "abstract": False,
                "indexes": [models.Index(fields=["tenant", "created_at"], name="billing_sub_tenant__1e35ce_idx")],
                "constraints": [
                    models.UniqueConstraint(fields=("tenant",), name="unique_active_subscription_row_per_tenant")
                ],
            },
        ),
    ]
