# Generated by Django 6.1 on 2026-09-09 16:44

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("billing", "0002_plan_razorpay_plan_id_subscription"),
        ("tenants", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="BillingWebhookEvent",
            fields=[
                ("id", models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("event_id", models.CharField(max_length=150, unique=True)),
                ("event_type", models.CharField(max_length=50)),
                (
                    "tenant",
                    models.ForeignKey(db_index=False, on_delete=django.db.models.deletion.CASCADE, to="tenants.tenant"),
                ),
            ],
            options={
                "db_table": "billing_webhook_event",
                "abstract": False,
                "indexes": [models.Index(fields=["tenant", "created_at"], name="billing_web_tenant__c58c78_idx")],
            },
        ),
    ]
