# Generated by Django 6.1 on 2026-09-09 17:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("billing", "0003_billingwebhookevent"),
    ]

    operations = [
        migrations.AddField(
            model_name="subscription",
            name="halted_at",
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
