# Generated by Django 6.1 on 2026-09-06 17:01

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("tenants", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="Widget",
            fields=[
                ("id", models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("name", models.CharField(max_length=100)),
                ("status", models.CharField(default="active", max_length=20)),
                (
                    "tenant",
                    models.ForeignKey(db_index=False, on_delete=django.db.models.deletion.CASCADE, to="tenants.tenant"),
                ),
            ],
            options={
                "abstract": False,
                "indexes": [
                    models.Index(fields=["tenant", "created_at"], name="core_widget_tenant__c650b5_idx"),
                    models.Index(fields=["tenant", "status"], name="core_widget_tenant__bd489f_idx"),
                ],
            },
        ),
    ]
