# Generated by Django 6.1 on 2026-09-06 15:51

import datetime
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0003_fix_rls_widget_policy"),
        ("tenants", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="widget",
            name="created_at",
            field=models.DateTimeField(
                auto_now_add=True,
                default=datetime.datetime(2026, 9, 6, 15, 51, 36, 132325, tzinfo=datetime.timezone.utc),
            ),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="widget",
            name="status",
            field=models.CharField(default="active", max_length=20),
        ),
        migrations.AlterField(
            model_name="widget",
            name="tenant",
            field=models.ForeignKey(db_index=False, on_delete=django.db.models.deletion.CASCADE, to="tenants.tenant"),
        ),
        migrations.AddIndex(
            model_name="widget",
            index=models.Index(fields=["tenant", "created_at"], name="core_widget_tenant__c650b5_idx"),
        ),
        migrations.AddIndex(
            model_name="widget",
            index=models.Index(fields=["tenant", "status"], name="core_widget_tenant__bd489f_idx"),
        ),
    ]
