# Generated by Django 6.1 on 2026-09-06 21:03

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("templates_registry", "0001_initial"),
        ("tenants", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="Page",
            fields=[
                ("id", models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "page_type",
                    models.CharField(
                        choices=[("landing", "Landing"), ("menu", "Menu"), ("blog", "Blog"), ("contact", "Contact")],
                        max_length=20,
                    ),
                ),
                ("enabled", models.BooleanField(default=True)),
                ("seo_meta", models.JSONField(blank=True, default=dict)),
                (
                    "tenant",
                    models.ForeignKey(db_index=False, on_delete=django.db.models.deletion.CASCADE, to="tenants.tenant"),
                ),
            ],
            options={
                "db_table": "cms_page",
                "abstract": False,
            },
        ),
        migrations.CreateModel(
            name="Section",
            fields=[
                ("id", models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("section_type", models.CharField(max_length=50)),
                ("ordered_position", models.PositiveIntegerField(default=0)),
                ("content", models.JSONField(blank=True, default=dict)),
                (
                    "page",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, related_name="sections", to="cms.page"
                    ),
                ),
                (
                    "tenant",
                    models.ForeignKey(db_index=False, on_delete=django.db.models.deletion.CASCADE, to="tenants.tenant"),
                ),
            ],
            options={
                "db_table": "cms_section",
                "ordering": ["ordered_position"],
                "abstract": False,
            },
        ),
        migrations.CreateModel(
            name="SiteConfig",
            fields=[
                ("id", models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("theme_config", models.JSONField(blank=True, default=dict)),
                (
                    "status",
                    models.CharField(choices=[("draft", "Draft"), ("live", "Live")], default="draft", max_length=20),
                ),
                (
                    "template_version",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT, to="templates_registry.templateversion"
                    ),
                ),
                (
                    "tenant",
                    models.ForeignKey(db_index=False, on_delete=django.db.models.deletion.CASCADE, to="tenants.tenant"),
                ),
            ],
            options={
                "db_table": "cms_site_config",
                "abstract": False,
            },
        ),
        migrations.CreateModel(
            name="MediaAsset",
            fields=[
                ("id", models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("storage_key", models.CharField(max_length=500)),
                ("url", models.URLField()),
                ("thumbnail_url", models.URLField(blank=True, null=True)),
                ("media_type", models.CharField(choices=[("image", "Image")], default="image", max_length=20)),
                ("width", models.PositiveIntegerField(blank=True, null=True)),
                ("height", models.PositiveIntegerField(blank=True, null=True)),
                (
                    "tenant",
                    models.ForeignKey(db_index=False, on_delete=django.db.models.deletion.CASCADE, to="tenants.tenant"),
                ),
            ],
            options={
                "db_table": "cms_media_asset",
                "abstract": False,
                "indexes": [models.Index(fields=["tenant", "created_at"], name="cms_media_a_tenant__ac9c28_idx")],
            },
        ),
        migrations.AddIndex(
            model_name="page",
            index=models.Index(fields=["tenant", "created_at"], name="cms_page_tenant__d0ab8a_idx"),
        ),
        migrations.AddConstraint(
            model_name="page",
            constraint=models.UniqueConstraint(fields=("tenant", "page_type"), name="one_page_per_type_per_tenant"),
        ),
        migrations.AddIndex(
            model_name="section",
            index=models.Index(fields=["tenant", "created_at"], name="cms_section_tenant__011e57_idx"),
        ),
        migrations.AddIndex(
            model_name="section",
            index=models.Index(fields=["tenant", "page", "ordered_position"], name="cms_section_tenant__bb83be_idx"),
        ),
        migrations.AddIndex(
            model_name="siteconfig",
            index=models.Index(fields=["tenant", "created_at"], name="cms_site_co_tenant__a6e179_idx"),
        ),
        migrations.AddConstraint(
            model_name="siteconfig",
            constraint=models.UniqueConstraint(fields=("tenant",), name="one_site_config_per_tenant"),
        ),
    ]
