# Generated by Django 6.1 on 2026-09-22 19:57

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("cms", "0001_initial"),
        ("tenants", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="BlogPost",
            fields=[
                ("id", models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("title", models.CharField(max_length=200)),
                ("slug", models.SlugField(max_length=220)),
                ("excerpt", models.CharField(blank=True, default="", max_length=300)),
                ("content", models.TextField(blank=True, default="")),
                ("cover_image", models.URLField(blank=True, null=True)),
                (
                    "status",
                    models.CharField(
                        choices=[("draft", "Draft"), ("published", "Published")], default="draft", max_length=20
                    ),
                ),
                ("published_at", models.DateTimeField(blank=True, null=True)),
                (
                    "tenant",
                    models.ForeignKey(db_index=False, on_delete=django.db.models.deletion.CASCADE, to="tenants.tenant"),
                ),
            ],
            options={
                "db_table": "cms_blog_post",
                "ordering": ["-published_at"],
                "abstract": False,
                "indexes": [
                    models.Index(fields=["tenant", "created_at"], name="cms_blog_po_tenant__4eb1bf_idx"),
                    models.Index(fields=["tenant", "status", "published_at"], name="cms_blog_po_tenant__33e790_idx"),
                ],
                "constraints": [models.UniqueConstraint(fields=("tenant", "slug"), name="unique_blog_slug_per_tenant")],
            },
        ),
    ]
