# Generated by Django 6.1 on 2026-09-06 11:05

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Tenant",
            fields=[
                ("id", models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ("slug", models.SlugField(max_length=63, unique=True)),
                ("name", models.CharField(max_length=255)),
                (
                    "status",
                    models.CharField(
                        choices=[("trial", "Trial"), ("active", "Active"), ("suspended", "Suspended")],
                        default="trial",
                        max_length=20,
                    ),
                ),
                (
                    "staff_account_mode",
                    models.CharField(
                        choices=[("shared", "Shared"), ("individual", "Individual")], default="shared", max_length=20
                    ),
                ),
                ("online_payment_enabled", models.BooleanField(default=False)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
            options={
                "db_table": "tenants_tenant",
            },
        ),
    ]
