# Generated by Django 6.1 on 2026-09-08 22:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("accounts", "0002_membership"),
    ]

    operations = [
        migrations.AddField(
            model_name="membership",
            name="is_shared_account",
            field=models.BooleanField(default=False),
        ),
    ]
