# Generated by Django 6.1 on 2026-09-06 20:55

import django.db.models.deletion
import templates_registry.models
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="TemplateRegistry",
            fields=[
                ("id", models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ("name", models.CharField(max_length=100, unique=True)),
                ("display_name", models.CharField(max_length=150)),
                ("preview_image", models.URLField(blank=True, null=True)),
                (
                    "status",
                    models.CharField(
                        choices=[("active", "Active"), ("deprecated", "Deprecated")], default="active", max_length=20
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
            ],
            options={
                "db_table": "templates_registry",
            },
        ),
        migrations.CreateModel(
            name="TemplateVersion",
            fields=[
                ("id", models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ("version", models.CharField(max_length=20)),
                (
                    "capability_manifest",
                    models.JSONField(validators=[templates_registry.models.validate_capability_manifest]),
                ),
                ("changelog", models.TextField(blank=True)),
                ("published_at", models.DateTimeField(auto_now_add=True)),
                (
                    "template",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="versions",
                        to="templates_registry.templateregistry",
                    ),
                ),
            ],
            options={
                "db_table": "templates_registry_version",
                "ordering": ["-published_at"],
                "constraints": [
                    models.UniqueConstraint(fields=("template", "version"), name="unique_template_version")
                ],
            },
        ),
    ]
