# Generated by Django 6.1 on 2026-09-22 18:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("templates_registry", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="templateversion",
            name="sequence",
            field=models.BigIntegerField(editable=False, null=True, unique=True),
        ),
    ]
