# Generated by Django 6.1 on 2026-09-07 16:22

import django.db.models.deletion
import tables.models
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("tenants", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="Table",
            fields=[
                ("id", models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("label", models.CharField(max_length=100)),
                (
                    "table_token",
                    models.CharField(
                        default=tables.models.generate_table_token, editable=False, max_length=64, unique=True
                    ),
                ),
                ("is_active", models.BooleanField(default=True)),
                (
                    "tenant",
                    models.ForeignKey(db_index=False, on_delete=django.db.models.deletion.CASCADE, to="tenants.tenant"),
                ),
            ],
            options={
                "db_table": "tables_table",
                "abstract": False,
                "indexes": [models.Index(fields=["tenant", "created_at"], name="tables_tabl_tenant__76ea94_idx")],
                "constraints": [
                    models.UniqueConstraint(fields=("tenant", "label"), name="unique_table_label_per_tenant")
                ],
            },
        ),
    ]
