# Generated by Django 6.1 on 2026-09-22 19:19

import django.db.models.deletion
import domains.models
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("tenants", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="Domain",
            fields=[
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("id", models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ("hostname", models.CharField(max_length=253, unique=True)),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("pending_verification", "Pending Verification"),
                            ("verified", "Verified"),
                            ("issuing_cert", "Issuing Certificate"),
                            ("active", "Active"),
                            ("failed", "Failed"),
                        ],
                        default="pending_verification",
                        max_length=30,
                    ),
                ),
                (
                    "verification_token",
                    models.CharField(default=domains.models.generate_verification_token, max_length=64),
                ),
                ("acm_certificate_arn", models.CharField(blank=True, default="", max_length=255)),
                ("failure_reason", models.TextField(blank=True, default="")),
                ("verified_at", models.DateTimeField(blank=True, null=True)),
                ("activated_at", models.DateTimeField(blank=True, null=True)),
                (
                    "tenant",
                    models.ForeignKey(db_index=False, on_delete=django.db.models.deletion.CASCADE, to="tenants.tenant"),
                ),
            ],
            options={
                "db_table": "domains_domain",
                "abstract": False,
                "indexes": [models.Index(fields=["tenant", "created_at"], name="domains_dom_tenant__b591d0_idx")],
                "constraints": [models.UniqueConstraint(fields=("tenant",), name="one_custom_domain_per_tenant")],
            },
        ),
    ]
