# Generated by Django 6.1 on 2026-09-06 23:39

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("cms", "0001_initial"),
        ("tenants", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="MenuCategory",
            fields=[
                ("id", models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("name", models.CharField(max_length=200)),
                ("ordered_position", models.PositiveIntegerField(default=0)),
                ("visible", models.BooleanField(default=True)),
                (
                    "tenant",
                    models.ForeignKey(db_index=False, on_delete=django.db.models.deletion.CASCADE, to="tenants.tenant"),
                ),
            ],
            options={
                "db_table": "menu_category",
                "ordering": ["ordered_position"],
                "abstract": False,
            },
        ),
        migrations.CreateModel(
            name="MenuItem",
            fields=[
                ("id", models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("name", models.CharField(max_length=200)),
                ("description", models.TextField(blank=True, default="")),
                ("price", models.DecimalField(decimal_places=2, max_digits=10)),
                ("is_available", models.BooleanField(default=True)),
                ("ordered_position", models.PositiveIntegerField(default=0)),
                (
                    "category",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, related_name="items", to="menu.menucategory"
                    ),
                ),
                (
                    "image",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="+",
                        to="cms.mediaasset",
                    ),
                ),
                (
                    "tenant",
                    models.ForeignKey(db_index=False, on_delete=django.db.models.deletion.CASCADE, to="tenants.tenant"),
                ),
            ],
            options={
                "db_table": "menu_item",
                "ordering": ["ordered_position"],
                "abstract": False,
            },
        ),
        migrations.AddIndex(
            model_name="menucategory",
            index=models.Index(fields=["tenant", "created_at"], name="menu_catego_tenant__393a6b_idx"),
        ),
        migrations.AddIndex(
            model_name="menucategory",
            index=models.Index(fields=["tenant", "ordered_position"], name="menu_catego_tenant__544dc6_idx"),
        ),
        migrations.AddConstraint(
            model_name="menucategory",
            constraint=models.UniqueConstraint(fields=("tenant", "name"), name="unique_category_name_per_tenant"),
        ),
        migrations.AddIndex(
            model_name="menuitem",
            index=models.Index(fields=["tenant", "created_at"], name="menu_item_tenant__45d4e2_idx"),
        ),
        migrations.AddIndex(
            model_name="menuitem",
            index=models.Index(fields=["tenant", "category", "ordered_position"], name="menu_item_tenant__d383a6_idx"),
        ),
    ]
