# Generated by Django 6.1 on 2026-09-07 17:10

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("menu", "0001_initial"),
        ("tenants", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="ModifierGroup",
            fields=[
                ("id", models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("name", models.CharField(max_length=100)),
                ("min_select", models.PositiveIntegerField(default=0)),
                ("max_select", models.PositiveIntegerField(default=1)),
                ("items", models.ManyToManyField(blank=True, related_name="modifier_groups", to="menu.menuitem")),
                (
                    "tenant",
                    models.ForeignKey(db_index=False, on_delete=django.db.models.deletion.CASCADE, to="tenants.tenant"),
                ),
            ],
            options={
                "db_table": "menu_modifier_group",
                "abstract": False,
            },
        ),
        migrations.CreateModel(
            name="Modifier",
            fields=[
                ("id", models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("name", models.CharField(max_length=100)),
                ("price_delta", models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                (
                    "tenant",
                    models.ForeignKey(db_index=False, on_delete=django.db.models.deletion.CASCADE, to="tenants.tenant"),
                ),
                (
                    "group",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, related_name="modifiers", to="menu.modifiergroup"
                    ),
                ),
            ],
            options={
                "db_table": "menu_modifier",
                "abstract": False,
            },
        ),
        migrations.AddIndex(
            model_name="modifiergroup",
            index=models.Index(fields=["tenant", "created_at"], name="menu_modifi_tenant__132eb0_idx"),
        ),
        migrations.AddConstraint(
            model_name="modifiergroup",
            constraint=models.UniqueConstraint(fields=("tenant", "name"), name="unique_modifier_group_name_per_tenant"),
        ),
        migrations.AddIndex(
            model_name="modifier",
            index=models.Index(fields=["tenant", "created_at"], name="menu_modifi_tenant__13c1c1_idx"),
        ),
        migrations.AddConstraint(
            model_name="modifier",
            constraint=models.UniqueConstraint(
                fields=("tenant", "group", "name"), name="unique_modifier_name_per_group"
            ),
        ),
    ]
