# Generated by Django 6.1 on 2026-09-07 21:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("orders", "0003_orderevent"),
    ]

    operations = [
        migrations.AddField(
            model_name="order",
            name="payment_mode",
            field=models.CharField(
                blank=True,
                choices=[("pay_now", "Pay Now"), ("pay_at_counter", "Pay at Counter")],
                max_length=20,
                null=True,
            ),
        ),
    ]
