# Generated by Django 6.1 on 2026-09-08 21:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("orders", "0004_order_payment_mode"),
        ("tables", "0001_initial"),
        ("tenants", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="order",
            name="updated_at",
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AddIndex(
            model_name="order",
            index=models.Index(fields=["tenant", "updated_at"], name="orders_orde_tenant__ddee6d_idx"),
        ),
    ]
